### ISSUE TITLE
ESP Text laggy

### ISSUE THREAD

**Issue by Marow** [Device9999/FiveM-External-ESP#9]
When i fly or drive to fast, the text on esp ist like jumping or something, looks like its not updating fast enaugh.

Where i can update that, so its updating the text faster... i think that can fix the laggy style when its updating faster :)

**Comment by Device9999** [comment]
It's external so obviously it's not running the same rate as the game.

**Comment by Marow** [comment]
But can i make it faster? @Device9999

**Comment by Marow** [comment]
Is there a way to get more FPS with it? I mean if you tab out, you see its there for like a sec... this cannot load faster? I only get around 10fps (frames in the menu showed that)

**Comment by Device9999** [comment]
get better pc

**Comment by Marow** [comment]
Have an RTX 2080 Ti and something, it looks like thats the shit of DirectX 9... to old and windows 10 do some shits

**Comment by Marow** [comment]
Okay fixed it... it was my BitDefender lol
